<?php

namespace App\Repositories\_Customer;


use App\Repositories\BaseLogic;
use App\Repositories\BaseRepository;
use App\Repositories\Rooms\RoomRepositoryInterface;

class RoomLogic extends BaseLogic
{
    public function __construct(
        RoomRepositoryInterface $model
    )
    {
        $this->model = $model;
    }

    public function getByQuery($params = [], $size = 25, $trash = BaseRepository::NO_TRASH)
    {
        return parent::getByQuery($params, $size, $trash); // TODO: Change the autogenerated stub
    }
}