<?php
/**
 * Created by PhpStorm.
 * User: DUCCHIEN-PC
 * Date: 1/16/2019
 * Time: 5:28 PM
 */

namespace App\Repositories\Seo;


use App\Repositories\BaseRepository;

class SeoRepository extends BaseRepository implements SeoRepositoryInterface
{
    /**
     * @var Blog
     */
    protected $model;

    /**
     * BlogRepository constructor.
     *
     * @param Blog $blog
     */
    public function __construct(
        Seo $seo
    ) {
        $this->model         = $seo;
    }

    /**
     *
     * @author ducchien0612 <ducchien0612@gmail.com>
     *
     * @param array $data
     * @return \App\Repositories\Eloquent
     */
    public function store($data = [])
    {
        $data['meta_keywords'] = json_encode($data['meta_keywords']);
        return parent::store($data);
    }

    /**
     *
     * @author ducchien0612 <ducchien0612@gmail.com>
     *
     * @param array $data
     * @return \App\Repositories\Eloquent
     */

    public function update($id, $data, $excepts = [], $only = [])
    {
        $data['meta_keywords'] = json_encode($data['meta_keywords']);
        return parent::update($id, $data, $excepts, $only); // TODO: Change the autogenerated stub
    }
    
}