<?php
/**
 * Created by PhpStorm.
 * User: DUCCHIEN-PC
 * Date: 1/16/2019
 * Time: 5:24 PM
 */

namespace App\Repositories\Settings;

use App\Repositories\BaseRepository;
use App\Events\AmazonS3_Upload_Event;

class SettingRepository extends BaseRepository implements SettingRepositoryInterface
{
    /**
     * @var Setting
     */
    protected $model;

    /**
     * SettingRepository constructor.
     * @param Setting $setting
     */
    public function __construct(
        Setting $setting
    ) {
        $this->model         = $setting;
    }


    /**
     *
     * @author ducchien0612 <ducchien0612@gmail.com>
     *
     * @param array $data
     * @return \App\Repositories\Eloquent
     */
    public function store($data = [])
    {
        $result= parent::getAll()->toArray();

        if (!empty($result))
        {
            throw new \Exception('Bạn phải xóa cài đặt trước đó thì mới có kiểu tao mới');
        }
        $data['homepage_image'] = isset($data['homepage_image']) ? $data['homepage_image'] : '';
        $data['image_logo']     = isset($data['image_logo']) ? $data['image_logo'] : '';

        $name_home = rand_name($data['homepage_image']);
        event(new AmazonS3_Upload_Event($name_home, $data['homepage_image']));
        $data['homepage_image']   = $name_home.'.jpeg';

        $name_logo = rand_name($data['image_logo']);
        event(new AmazonS3_Upload_Event($name_logo, $data['image_logo']));
        $data['image_logo']   = $name_logo.'.jpeg';
        if (!empty($data)) {
            $data['homepage_image']  = $data['homepage_image'];
            $data['image_logo']      = $data['image_logo'];
            $data['contact_email']   = isset($data['contact_email']) ? json_encode($data['contact_email']) : '';
            $data['contact_hotline'] = isset($data['contact_hotline']) ? json_encode($data['contact_hotline']) : '';
            $data['bank_account']    = isset($data['bank_account']) ? json_encode($data['bank_account']): '';
            $data['meta_keywords']   = isset($data['meta_keywords']) ? $data['meta_keywords'] : '';
        }

        return parent::store($data);
    }

    /**
     *
     * @author ducchien0612 <ducchien0612@gmail.com>
     *
     * @param array $data
     * @return \App\Repositories\Eloquent
     */
    public function updateSettings($id, $data = [], $excepts = [], $only = [])
    {
        if (!empty($data)) {
            $name_home = rand_name($data['homepage_image']);
            event(new AmazonS3_Upload_Event($name_home, $data['homepage_image']));
            $data['homepage_image']   = $name_home.'.jpeg';

            $name_logo = rand_name($data['image_logo']);
            event(new AmazonS3_Upload_Event($name_logo, $data['image_logo']));
            $data['image_logo']   = $name_logo.'.jpeg';

            if (isset($data['contact_email'])) {
                $data['contact_email'] = json_encode($data['contact_email']);
            }

            if (isset($data['contact_hotline'])) {
                $data['contact_hotline'] = json_encode($data['contact_hotline']);
            }

            if (isset($data['bank_account'])) {
                $data['bank_account'] = json_encode($data['bank_account']);
            }

            if (isset($data['meta_keywords'])) {
                $data['meta_keywords'] = json_encode($data['meta_keywords']);
            }
        }
        return parent::update($id, $data, $excepts, $only); // TODO: Change the autogenerated stub
    }
}
